name: "Olympix Mutation Test Generator"
description: "Perform code analysis in Solidity projects to generate mutation tests"
branding:
  icon: 'x'
  color: 'purple'
inputs:
  args:
    description: "Arguments to customize unit test generator"
    default: --confirm-all
runs:
  using: "docker"
  image: "docker://olympix/integrated-security:latest"
  env:
    OLYMPIX_INTEGRATION_ORIGIN: "gha"
  args:
  - generate-mutation-tests
  - ${{ inputs.args }}
