name: "Olympix Mutation Test Generator"
description: "Perform code analysis in Solidity projects to generate mutation tests"
branding:
  icon: 'x'
  color: 'purple'
inputs:
  args:
    description: "Arguments to customize unit test generator"
    default: --confirm-all
runs:
  using: "docker"
  image: "docker://olympix/integrated-security:test-latest"
  env:
    OLYMPIX_INTEGRATION_ORIGIN: "gha"
    OLYMPIX_API_URL: "https://api.olympixscantest.com/api/v1"
    OLYMPIX_API_WS_URL: "wss://api.olympixscantest.com/api/v1/client-ide-ws" 
  args:
  - generate-mutation-tests
  - ${{ inputs.args }}
